apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wanderlust
  creationTimestamp: null
  labels:
    app: backend
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: madhupdevops/wanderlust-backend-beta:v2.1.0
        name: backend
        ports:
        - containerPort: 8080
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: wanderlust
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31100
