apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage-claim
  namespace: wanderlust
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
